### PR TITLE
Hash#update() vs Hash#[]=

### PR DESCRIPTION
**Pull request by manjunath724**
Hash#update is an alias for Hash#merge!
Ergo, the suggestions for Hash#update should be similar to Hash#merge!

Ref https://github.com/DamirSvrtan/fasterer/issues/82

Link to Fast-Ruby PR : https://github.com/JuanitoFatas/fast-ruby/pull/195

### CODE REVIEW

**Comment by DamirSvrtan** [comment]
Let me know once the Fast Ruby PR merges in, and we can then continue on!

**Comment by hlascelles** [comment]
It was merged last April :+1: 

Keen for a merge please!

**Comment by ManjunathPrakash** [comment]
@DamirSvrtan Fast Ruby [PR](https://github.com/fastruby/fast-ruby/pull/195) was merged, can we please merge this PR too? Thank you in advance.

**Comment by DamirSvrtan** [comment]
I have merged it, and I might have done it without thinking this through enough! I have realized though how many issues this might cause, as update is such a commonly used method name in Ruby world (especially in Active Record).

Before I cut a new version of fasterer with this update, @manjunath724, @hlascelles, can you all chime in a bit with your thoughts on whether this will clash a bit too much and produce false positives?

**Pull request merged**
