### PR TITLE
Update to ruby_parser 3.14.0

### PR DESCRIPTION
**Pull request by mgrachev**

### CODE REVIEW

**Comment by DamirSvrtan** [comment]
Hi @mgrachev, thanks for the contribution!

Can you provide more context on the upgrade, is the current parser not working on some versions?

**Comment by DamirSvrtan** [comment]
I am hesitant to merge this in as if there are no real issues, I don't want to bump everybody's ruby parser version.

If you are seeing bugs due to not being on the latest version, please let me know.

**Comment by mgrachev** [comment]
Hi! I've faced a problem when I used fasterer with pronto via https://github.com/prontolabs/pronto-fasterer. But that problem was related to ruby_parser's version below 3.13.0. So, I decided to upgrade the ruby_parser to the latest version, just in case.

**Comment by DamirSvrtan** [comment]
Alright, thanks for the context. In that case, I'd close this issue and reopen it if there are any issues with the ruby_parser 3.13.0. Thanks for the contribution anyhow!

**Pull request closed without merging**
